#ifndef GUARD_CONSTANTS_POKEMON_SPRITE_VISUALIZER_H
#define GUARD_CONSTANTS_POKEMON_SPRITE_VISUALIZER_H

//Defines
#define VISUALIZER_MON_BACK_X 62
#define VISUALIZER_MON_BACK_Y 80
#define VISUALIZER_ICON_X 224
#define VISUALIZER_ICON_Y 144
#define VISUALIZER_FOLLOWER_X 176
#define VISUALIZER_FOLLOWER_Y 128

#define MODIFY_DIGITS_MAX 4
#define MODIFY_DIGITS_ARROW_X 129
#define MODIFY_DIGITS_ARROW1_Y 94
#define MODIFY_DIGITS_ARROW2_Y 113

#define OPTIONS_ARROW_1_X 4
#define OPTIONS_ARROW_2_X 236
#define OPTIONS_ARROW_Y 119

#define GENDER_MALE 0
#define GENDER_FEMALE 1
#define MON_PIC_BACK 0
#define MON_PIC_FRONT 1

//Sprite offset
#define MAX_Y_OFFSET 20

//Windows
#define WIN_NAME_NUMBERS 0
#define WIN_INSTRUCTIONS 1
#define WIN_BOTTOM_LEFT 2
#define WIN_BOTTOM_RIGHT 3
#define WIN_FOOTPRINT 4
#define WIN_END 5

//Battle backgrounds
#define MAP_BATTLE_SCENE_NORMAL       0
#define MAP_BATTLE_SCENE_GYM          1
#define MAP_BATTLE_SCENE_MAGMA        2
#define MAP_BATTLE_SCENE_AQUA         3
#define MAP_BATTLE_SCENE_BROCK        4
#define MAP_BATTLE_SCENE_MISTY        5
#define MAP_BATTLE_SCENE_SURGE        6
#define MAP_BATTLE_SCENE_ERIKA        7
#define MAP_BATTLE_SCENE_KOGA         8
#define MAP_BATTLE_SCENE_SABRINA      9
#define MAP_BATTLE_SCENE_BLAINE       10
#define MAP_BATTLE_SCENE_GIOVANNI     11
#define MAP_BATTLE_SCENE_LORELEI      12
#define MAP_BATTLE_SCENE_BRUNO        13
#define MAP_BATTLE_SCENE_AGATHA       14
#define MAP_BATTLE_SCENE_LANCE        15
#define MAP_BATTLE_SCENE_FRONTIER     16
#define MAP_BATTLE_SCENE_CHAMPION     17
#define MAP_BATTLE_SCENE_GROUDON      18
#define MAP_BATTLE_SCENE_KYOGRE       19
#define MAP_BATTLE_SCENE_RAYQUAZA     20

#endif // GUARD_CONSTANTS_POKEMON_SPRITE_VISUALIZER_H
