#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(OVERHEAT) \
    F(FLAME_CHARGE) \
    F(DRAIN_KISS) \
    F(ICY_WIND) \
    F(ACROBATICS) \
    F(STRUGGLE_BUG) \
    F(TRAILBLAZE) \
    F(CHILLING_WATER) \
    F(CHARGE_BEAM) \
    F(BULLDOZE) \
    F(HEX) \
    F(DRAGON_TAIL) \
    F(VOLT_SWITCH) \
    F(SHADOW_CLAW) \
    F(U_TURN) \
    F(AIR_SLASH) \
    F(DAZZLING_GLEAM) \
    F(POISON_JAB) \
    F(FLASH_CANNON) \
    F(DARK_PULSE) \
    F(IRON_HEAD) \
    F(POWER_GEM) \
    F(GUNK_SHOT) \
    F(X_SCISSOR) \
    F(DRILL_RUN) \
    F(CRUNCH) \
    F(LIQUIDATION) \
    F(AURA_SPHERE) \
    F(STEALTH_ROCK) \
    F(TAILWIND) \
    F(DRAGON_PULSE) \
    F(HEAT_WAVE) \
    F(ENERGY_BALL) \
    F(PLAY_ROUGH) \
    F(EARTH_POWER) \
    F(SWORDS_DANCE) \
    F(NASTY_PLOT) \
    F(HYDRO_PUMP) \
    F(WILD_CHARGE) \
    F(ROCK_SLIDE) \
    F(STONE_EDGE) \
    F(PHANTOM_FORCE) \
    F(OUTRAGE) \
    F(FOCUS_BLAST) \
    F(LEAF_STORM) \
    F(HURRICANE) \
    F(TRICK_ROOM) \
    F(BUG_BUZZ) \
    F(CLOSE_COMBAT) \
    F(BRAVE_BIRD) \
    F(FLARE_BLITZ)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
